[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[allowlists]]
description = "Directories to ignore during Gitleaks scans"
paths = [
  '''.*\.env''',
  '''artifacts/''',
  '''.*cache/''',
  '''.*img/''',
  '''.*node_modules/''',
  '''.git/''',
  '''.*\.vs/''',
]
